# Generated by Django 4.1 on 2023-10-30 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CUser",
            new_name="User",
        ),
    ]
